name: Create PR from develop to main

# develop 브랜치의 tokens.json 파일에 대한 push 감지
on:
  push:
    branches:
      - develop
    paths:
      - 'tokens.json'
      
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      # 디자인 파일 변환 후 생성된 파일도 push해서 main 브랜치로 병합하는 PR을 생성
      - name: Run Token Transformer
        run: |
            rm -rf theme
            npx token-transformer tokens.json theme/core.json global
            npx token-transformer tokens.json theme/light.json global,light global
            npx token-transformer tokens.json theme/dark.json global,dark global
            
            git config --global user.name "hyeungeunKim" 
            git config --global user.email "gusrms126@naver.com"
            git add .
            git commit -m '피그마 디자인 파일 변환'
            git push
        env: 
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pull Request
        run: gh pr create -B main -H develop --title '디자인 토큰 변환' --body '디자인 파일 업데이트 후 토큰 변환'
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
